/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as _authedRouteImport } from './routes/__authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProjectsRouteImport } from './routes/api.projects'
import { Route as ApiDemoNamesRouteImport } from './routes/api.demo-names'
import { Route as _authtedOrganizationsRouteImport } from './routes/__authted/organizations'
import { Route as _authtedOrgRouteImport } from './routes/__authted/$org'
import { Route as _authtedOrgIndexRouteImport } from './routes/__authted/$org/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as _authtedOrgTelmentaryRouteImport } from './routes/__authted/$org/telmentary'
import { Route as _authtedOrgSettingsRouteImport } from './routes/__authted/$org/settings'
import { Route as _authtedOrgTelmentaryIndexRouteImport } from './routes/__authted/$org/telmentary/index'
import { Route as _authtedOrgSettingsIndexRouteImport } from './routes/__authted/$org/settings/index'
import { Route as _authtedOrgTelmentaryProjectIdRouteImport } from './routes/__authted/$org/telmentary/$projectId'
import { Route as _authtedOrgSettingsTeamRouteImport } from './routes/__authted/$org/settings/team'
import { Route as _authtedOrgSettingsSupportRouteImport } from './routes/__authted/$org/settings/support'
import { Route as _authtedOrgSettingsSecurityRouteImport } from './routes/__authted/$org/settings/security'
import { Route as _authtedOrgSettingsGeneralRouteImport } from './routes/__authted/$org/settings/general'
import { Route as _authtedOrgSettingsBillingRouteImport } from './routes/__authted/$org/settings/billing'
import { Route as _authtedOrgTelmentaryProjectIdIndexRouteImport } from './routes/__authted/$org/telmentary/$projectId/index'
import { Route as _authtedOrgTelmentaryProjectIdTracesRouteImport } from './routes/__authted/$org/telmentary/$projectId/traces'
import { Route as _authtedOrgTelmentaryProjectIdSettingsRouteImport } from './routes/__authted/$org/telmentary/$projectId/settings'
import { Route as _authtedOrgTelmentaryProjectIdLogsRouteImport } from './routes/__authted/$org/telmentary/$projectId/logs'
import { Route as _authtedOrgTelmentaryProjectIdAnalyticsRouteImport } from './routes/__authted/$org/telmentary/$projectId/analytics'
import { Route as _authtedOrgTelmentaryProjectIdAlertsRouteImport } from './routes/__authted/$org/telmentary/$projectId/alerts'
import { Route as _authtedOrgTelmentaryProjectIdSettingsIndexRouteImport } from './routes/__authted/$org/telmentary/$projectId/settings/index'
import { Route as _authtedOrgTelmentaryProjectIdSettingsIntegrationsRouteImport } from './routes/__authted/$org/telmentary/$projectId/settings/integrations'
import { Route as _authtedOrgTelmentaryProjectIdSettingsGeneralRouteImport } from './routes/__authted/$org/telmentary/$projectId/settings/general'
import { Route as _authtedOrgTelmentaryProjectIdSettingsDataRetentionRouteImport } from './routes/__authted/$org/telmentary/$projectId/settings/data-retention'
import { Route as _authtedOrgTelmentaryProjectIdSettingsApiKeysRouteImport } from './routes/__authted/$org/telmentary/$projectId/settings/api-keys'
import { Route as _authtedOrgTelmentaryProjectIdSettingsAlertsRouteImport } from './routes/__authted/$org/telmentary/$projectId/settings/alerts'
import { Route as _authtedOrgTelmentaryProjectIdSettingsAccessControlRouteImport } from './routes/__authted/$org/telmentary/$projectId/settings/access-control'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const _authedRoute = _authedRouteImport.update({
  id: '/__authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoNamesRoute = ApiDemoNamesRouteImport.update({
  id: '/api/demo-names',
  path: '/api/demo-names',
  getParentRoute: () => rootRouteImport,
} as any)
const _authtedOrganizationsRoute = _authtedOrganizationsRouteImport.update({
  id: '/__authted/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const _authtedOrgRoute = _authtedOrgRouteImport.update({
  id: '/__authted/$org',
  path: '/$org',
  getParentRoute: () => rootRouteImport,
} as any)
const _authtedOrgIndexRoute = _authtedOrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _authtedOrgRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const _authtedOrgTelmentaryRoute = _authtedOrgTelmentaryRouteImport.update({
  id: '/telmentary',
  path: '/telmentary',
  getParentRoute: () => _authtedOrgRoute,
} as any)
const _authtedOrgSettingsRoute = _authtedOrgSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => _authtedOrgRoute,
} as any)
const _authtedOrgTelmentaryIndexRoute =
  _authtedOrgTelmentaryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => _authtedOrgTelmentaryRoute,
  } as any)
const _authtedOrgSettingsIndexRoute =
  _authtedOrgSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => _authtedOrgSettingsRoute,
  } as any)
const _authtedOrgTelmentaryProjectIdRoute =
  _authtedOrgTelmentaryProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => _authtedOrgTelmentaryRoute,
  } as any)
const _authtedOrgSettingsTeamRoute = _authtedOrgSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => _authtedOrgSettingsRoute,
} as any)
const _authtedOrgSettingsSupportRoute =
  _authtedOrgSettingsSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => _authtedOrgSettingsRoute,
  } as any)
const _authtedOrgSettingsSecurityRoute =
  _authtedOrgSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => _authtedOrgSettingsRoute,
  } as any)
const _authtedOrgSettingsGeneralRoute =
  _authtedOrgSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => _authtedOrgSettingsRoute,
  } as any)
const _authtedOrgSettingsBillingRoute =
  _authtedOrgSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => _authtedOrgSettingsRoute,
  } as any)
const _authtedOrgTelmentaryProjectIdIndexRoute =
  _authtedOrgTelmentaryProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => _authtedOrgTelmentaryProjectIdRoute,
  } as any)
const _authtedOrgTelmentaryProjectIdTracesRoute =
  _authtedOrgTelmentaryProjectIdTracesRouteImport.update({
    id: '/traces',
    path: '/traces',
    getParentRoute: () => _authtedOrgTelmentaryProjectIdRoute,
  } as any)
const _authtedOrgTelmentaryProjectIdSettingsRoute =
  _authtedOrgTelmentaryProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => _authtedOrgTelmentaryProjectIdRoute,
  } as any)
const _authtedOrgTelmentaryProjectIdLogsRoute =
  _authtedOrgTelmentaryProjectIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => _authtedOrgTelmentaryProjectIdRoute,
  } as any)
const _authtedOrgTelmentaryProjectIdAnalyticsRoute =
  _authtedOrgTelmentaryProjectIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => _authtedOrgTelmentaryProjectIdRoute,
  } as any)
const _authtedOrgTelmentaryProjectIdAlertsRoute =
  _authtedOrgTelmentaryProjectIdAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => _authtedOrgTelmentaryProjectIdRoute,
  } as any)
const _authtedOrgTelmentaryProjectIdSettingsIndexRoute =
  _authtedOrgTelmentaryProjectIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => _authtedOrgTelmentaryProjectIdSettingsRoute,
  } as any)
const _authtedOrgTelmentaryProjectIdSettingsIntegrationsRoute =
  _authtedOrgTelmentaryProjectIdSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => _authtedOrgTelmentaryProjectIdSettingsRoute,
  } as any)
const _authtedOrgTelmentaryProjectIdSettingsGeneralRoute =
  _authtedOrgTelmentaryProjectIdSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => _authtedOrgTelmentaryProjectIdSettingsRoute,
  } as any)
const _authtedOrgTelmentaryProjectIdSettingsDataRetentionRoute =
  _authtedOrgTelmentaryProjectIdSettingsDataRetentionRouteImport.update({
    id: '/data-retention',
    path: '/data-retention',
    getParentRoute: () => _authtedOrgTelmentaryProjectIdSettingsRoute,
  } as any)
const _authtedOrgTelmentaryProjectIdSettingsApiKeysRoute =
  _authtedOrgTelmentaryProjectIdSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => _authtedOrgTelmentaryProjectIdSettingsRoute,
  } as any)
const _authtedOrgTelmentaryProjectIdSettingsAlertsRoute =
  _authtedOrgTelmentaryProjectIdSettingsAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => _authtedOrgTelmentaryProjectIdSettingsRoute,
  } as any)
const _authtedOrgTelmentaryProjectIdSettingsAccessControlRoute =
  _authtedOrgTelmentaryProjectIdSettingsAccessControlRouteImport.update({
    id: '/access-control',
    path: '/access-control',
    getParentRoute: () => _authtedOrgTelmentaryProjectIdSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/$org': typeof _authtedOrgRouteWithChildren
  '/organizations': typeof _authtedOrganizationsRoute
  '/api/demo-names': typeof ApiDemoNamesRoute
  '/api/projects': typeof ApiProjectsRoute
  '/$org/settings': typeof _authtedOrgSettingsRouteWithChildren
  '/$org/telmentary': typeof _authtedOrgTelmentaryRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$org/': typeof _authtedOrgIndexRoute
  '/$org/settings/billing': typeof _authtedOrgSettingsBillingRoute
  '/$org/settings/general': typeof _authtedOrgSettingsGeneralRoute
  '/$org/settings/security': typeof _authtedOrgSettingsSecurityRoute
  '/$org/settings/support': typeof _authtedOrgSettingsSupportRoute
  '/$org/settings/team': typeof _authtedOrgSettingsTeamRoute
  '/$org/telmentary/$projectId': typeof _authtedOrgTelmentaryProjectIdRouteWithChildren
  '/$org/settings/': typeof _authtedOrgSettingsIndexRoute
  '/$org/telmentary/': typeof _authtedOrgTelmentaryIndexRoute
  '/$org/telmentary/$projectId/alerts': typeof _authtedOrgTelmentaryProjectIdAlertsRoute
  '/$org/telmentary/$projectId/analytics': typeof _authtedOrgTelmentaryProjectIdAnalyticsRoute
  '/$org/telmentary/$projectId/logs': typeof _authtedOrgTelmentaryProjectIdLogsRoute
  '/$org/telmentary/$projectId/settings': typeof _authtedOrgTelmentaryProjectIdSettingsRouteWithChildren
  '/$org/telmentary/$projectId/traces': typeof _authtedOrgTelmentaryProjectIdTracesRoute
  '/$org/telmentary/$projectId/': typeof _authtedOrgTelmentaryProjectIdIndexRoute
  '/$org/telmentary/$projectId/settings/access-control': typeof _authtedOrgTelmentaryProjectIdSettingsAccessControlRoute
  '/$org/telmentary/$projectId/settings/alerts': typeof _authtedOrgTelmentaryProjectIdSettingsAlertsRoute
  '/$org/telmentary/$projectId/settings/api-keys': typeof _authtedOrgTelmentaryProjectIdSettingsApiKeysRoute
  '/$org/telmentary/$projectId/settings/data-retention': typeof _authtedOrgTelmentaryProjectIdSettingsDataRetentionRoute
  '/$org/telmentary/$projectId/settings/general': typeof _authtedOrgTelmentaryProjectIdSettingsGeneralRoute
  '/$org/telmentary/$projectId/settings/integrations': typeof _authtedOrgTelmentaryProjectIdSettingsIntegrationsRoute
  '/$org/telmentary/$projectId/settings/': typeof _authtedOrgTelmentaryProjectIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/organizations': typeof _authtedOrganizationsRoute
  '/api/demo-names': typeof ApiDemoNamesRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$org': typeof _authtedOrgIndexRoute
  '/$org/settings/billing': typeof _authtedOrgSettingsBillingRoute
  '/$org/settings/general': typeof _authtedOrgSettingsGeneralRoute
  '/$org/settings/security': typeof _authtedOrgSettingsSecurityRoute
  '/$org/settings/support': typeof _authtedOrgSettingsSupportRoute
  '/$org/settings/team': typeof _authtedOrgSettingsTeamRoute
  '/$org/settings': typeof _authtedOrgSettingsIndexRoute
  '/$org/telmentary': typeof _authtedOrgTelmentaryIndexRoute
  '/$org/telmentary/$projectId/alerts': typeof _authtedOrgTelmentaryProjectIdAlertsRoute
  '/$org/telmentary/$projectId/analytics': typeof _authtedOrgTelmentaryProjectIdAnalyticsRoute
  '/$org/telmentary/$projectId/logs': typeof _authtedOrgTelmentaryProjectIdLogsRoute
  '/$org/telmentary/$projectId/traces': typeof _authtedOrgTelmentaryProjectIdTracesRoute
  '/$org/telmentary/$projectId': typeof _authtedOrgTelmentaryProjectIdIndexRoute
  '/$org/telmentary/$projectId/settings/access-control': typeof _authtedOrgTelmentaryProjectIdSettingsAccessControlRoute
  '/$org/telmentary/$projectId/settings/alerts': typeof _authtedOrgTelmentaryProjectIdSettingsAlertsRoute
  '/$org/telmentary/$projectId/settings/api-keys': typeof _authtedOrgTelmentaryProjectIdSettingsApiKeysRoute
  '/$org/telmentary/$projectId/settings/data-retention': typeof _authtedOrgTelmentaryProjectIdSettingsDataRetentionRoute
  '/$org/telmentary/$projectId/settings/general': typeof _authtedOrgTelmentaryProjectIdSettingsGeneralRoute
  '/$org/telmentary/$projectId/settings/integrations': typeof _authtedOrgTelmentaryProjectIdSettingsIntegrationsRoute
  '/$org/telmentary/$projectId/settings': typeof _authtedOrgTelmentaryProjectIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__authed': typeof _authedRoute
  '/onboarding': typeof OnboardingRoute
  '/__authted/$org': typeof _authtedOrgRouteWithChildren
  '/__authted/organizations': typeof _authtedOrganizationsRoute
  '/api/demo-names': typeof ApiDemoNamesRoute
  '/api/projects': typeof ApiProjectsRoute
  '/__authted/$org/settings': typeof _authtedOrgSettingsRouteWithChildren
  '/__authted/$org/telmentary': typeof _authtedOrgTelmentaryRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/__authted/$org/': typeof _authtedOrgIndexRoute
  '/__authted/$org/settings/billing': typeof _authtedOrgSettingsBillingRoute
  '/__authted/$org/settings/general': typeof _authtedOrgSettingsGeneralRoute
  '/__authted/$org/settings/security': typeof _authtedOrgSettingsSecurityRoute
  '/__authted/$org/settings/support': typeof _authtedOrgSettingsSupportRoute
  '/__authted/$org/settings/team': typeof _authtedOrgSettingsTeamRoute
  '/__authted/$org/telmentary/$projectId': typeof _authtedOrgTelmentaryProjectIdRouteWithChildren
  '/__authted/$org/settings/': typeof _authtedOrgSettingsIndexRoute
  '/__authted/$org/telmentary/': typeof _authtedOrgTelmentaryIndexRoute
  '/__authted/$org/telmentary/$projectId/alerts': typeof _authtedOrgTelmentaryProjectIdAlertsRoute
  '/__authted/$org/telmentary/$projectId/analytics': typeof _authtedOrgTelmentaryProjectIdAnalyticsRoute
  '/__authted/$org/telmentary/$projectId/logs': typeof _authtedOrgTelmentaryProjectIdLogsRoute
  '/__authted/$org/telmentary/$projectId/settings': typeof _authtedOrgTelmentaryProjectIdSettingsRouteWithChildren
  '/__authted/$org/telmentary/$projectId/traces': typeof _authtedOrgTelmentaryProjectIdTracesRoute
  '/__authted/$org/telmentary/$projectId/': typeof _authtedOrgTelmentaryProjectIdIndexRoute
  '/__authted/$org/telmentary/$projectId/settings/access-control': typeof _authtedOrgTelmentaryProjectIdSettingsAccessControlRoute
  '/__authted/$org/telmentary/$projectId/settings/alerts': typeof _authtedOrgTelmentaryProjectIdSettingsAlertsRoute
  '/__authted/$org/telmentary/$projectId/settings/api-keys': typeof _authtedOrgTelmentaryProjectIdSettingsApiKeysRoute
  '/__authted/$org/telmentary/$projectId/settings/data-retention': typeof _authtedOrgTelmentaryProjectIdSettingsDataRetentionRoute
  '/__authted/$org/telmentary/$projectId/settings/general': typeof _authtedOrgTelmentaryProjectIdSettingsGeneralRoute
  '/__authted/$org/telmentary/$projectId/settings/integrations': typeof _authtedOrgTelmentaryProjectIdSettingsIntegrationsRoute
  '/__authted/$org/telmentary/$projectId/settings/': typeof _authtedOrgTelmentaryProjectIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/$org'
    | '/organizations'
    | '/api/demo-names'
    | '/api/projects'
    | '/$org/settings'
    | '/$org/telmentary'
    | '/api/auth/$'
    | '/$org/'
    | '/$org/settings/billing'
    | '/$org/settings/general'
    | '/$org/settings/security'
    | '/$org/settings/support'
    | '/$org/settings/team'
    | '/$org/telmentary/$projectId'
    | '/$org/settings/'
    | '/$org/telmentary/'
    | '/$org/telmentary/$projectId/alerts'
    | '/$org/telmentary/$projectId/analytics'
    | '/$org/telmentary/$projectId/logs'
    | '/$org/telmentary/$projectId/settings'
    | '/$org/telmentary/$projectId/traces'
    | '/$org/telmentary/$projectId/'
    | '/$org/telmentary/$projectId/settings/access-control'
    | '/$org/telmentary/$projectId/settings/alerts'
    | '/$org/telmentary/$projectId/settings/api-keys'
    | '/$org/telmentary/$projectId/settings/data-retention'
    | '/$org/telmentary/$projectId/settings/general'
    | '/$org/telmentary/$projectId/settings/integrations'
    | '/$org/telmentary/$projectId/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/organizations'
    | '/api/demo-names'
    | '/api/projects'
    | '/api/auth/$'
    | '/$org'
    | '/$org/settings/billing'
    | '/$org/settings/general'
    | '/$org/settings/security'
    | '/$org/settings/support'
    | '/$org/settings/team'
    | '/$org/settings'
    | '/$org/telmentary'
    | '/$org/telmentary/$projectId/alerts'
    | '/$org/telmentary/$projectId/analytics'
    | '/$org/telmentary/$projectId/logs'
    | '/$org/telmentary/$projectId/traces'
    | '/$org/telmentary/$projectId'
    | '/$org/telmentary/$projectId/settings/access-control'
    | '/$org/telmentary/$projectId/settings/alerts'
    | '/$org/telmentary/$projectId/settings/api-keys'
    | '/$org/telmentary/$projectId/settings/data-retention'
    | '/$org/telmentary/$projectId/settings/general'
    | '/$org/telmentary/$projectId/settings/integrations'
    | '/$org/telmentary/$projectId/settings'
  id:
    | '__root__'
    | '/'
    | '/__authed'
    | '/onboarding'
    | '/__authted/$org'
    | '/__authted/organizations'
    | '/api/demo-names'
    | '/api/projects'
    | '/__authted/$org/settings'
    | '/__authted/$org/telmentary'
    | '/api/auth/$'
    | '/__authted/$org/'
    | '/__authted/$org/settings/billing'
    | '/__authted/$org/settings/general'
    | '/__authted/$org/settings/security'
    | '/__authted/$org/settings/support'
    | '/__authted/$org/settings/team'
    | '/__authted/$org/telmentary/$projectId'
    | '/__authted/$org/settings/'
    | '/__authted/$org/telmentary/'
    | '/__authted/$org/telmentary/$projectId/alerts'
    | '/__authted/$org/telmentary/$projectId/analytics'
    | '/__authted/$org/telmentary/$projectId/logs'
    | '/__authted/$org/telmentary/$projectId/settings'
    | '/__authted/$org/telmentary/$projectId/traces'
    | '/__authted/$org/telmentary/$projectId/'
    | '/__authted/$org/telmentary/$projectId/settings/access-control'
    | '/__authted/$org/telmentary/$projectId/settings/alerts'
    | '/__authted/$org/telmentary/$projectId/settings/api-keys'
    | '/__authted/$org/telmentary/$projectId/settings/data-retention'
    | '/__authted/$org/telmentary/$projectId/settings/general'
    | '/__authted/$org/telmentary/$projectId/settings/integrations'
    | '/__authted/$org/telmentary/$projectId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _authedRoute: typeof _authedRoute
  OnboardingRoute: typeof OnboardingRoute
  _authtedOrgRoute: typeof _authtedOrgRouteWithChildren
  _authtedOrganizationsRoute: typeof _authtedOrganizationsRoute
  ApiDemoNamesRoute: typeof ApiDemoNamesRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authed': {
      id: '/__authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _authedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo-names': {
      id: '/api/demo-names'
      path: '/api/demo-names'
      fullPath: '/api/demo-names'
      preLoaderRoute: typeof ApiDemoNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authted/organizations': {
      id: '/__authted/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof _authtedOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authted/$org': {
      id: '/__authted/$org'
      path: '/$org'
      fullPath: '/$org'
      preLoaderRoute: typeof _authtedOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authted/$org/': {
      id: '/__authted/$org/'
      path: '/'
      fullPath: '/$org/'
      preLoaderRoute: typeof _authtedOrgIndexRouteImport
      parentRoute: typeof _authtedOrgRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authted/$org/telmentary': {
      id: '/__authted/$org/telmentary'
      path: '/telmentary'
      fullPath: '/$org/telmentary'
      preLoaderRoute: typeof _authtedOrgTelmentaryRouteImport
      parentRoute: typeof _authtedOrgRoute
    }
    '/__authted/$org/settings': {
      id: '/__authted/$org/settings'
      path: '/settings'
      fullPath: '/$org/settings'
      preLoaderRoute: typeof _authtedOrgSettingsRouteImport
      parentRoute: typeof _authtedOrgRoute
    }
    '/__authted/$org/telmentary/': {
      id: '/__authted/$org/telmentary/'
      path: '/'
      fullPath: '/$org/telmentary/'
      preLoaderRoute: typeof _authtedOrgTelmentaryIndexRouteImport
      parentRoute: typeof _authtedOrgTelmentaryRoute
    }
    '/__authted/$org/settings/': {
      id: '/__authted/$org/settings/'
      path: '/'
      fullPath: '/$org/settings/'
      preLoaderRoute: typeof _authtedOrgSettingsIndexRouteImport
      parentRoute: typeof _authtedOrgSettingsRoute
    }
    '/__authted/$org/telmentary/$projectId': {
      id: '/__authted/$org/telmentary/$projectId'
      path: '/$projectId'
      fullPath: '/$org/telmentary/$projectId'
      preLoaderRoute: typeof _authtedOrgTelmentaryProjectIdRouteImport
      parentRoute: typeof _authtedOrgTelmentaryRoute
    }
    '/__authted/$org/settings/team': {
      id: '/__authted/$org/settings/team'
      path: '/team'
      fullPath: '/$org/settings/team'
      preLoaderRoute: typeof _authtedOrgSettingsTeamRouteImport
      parentRoute: typeof _authtedOrgSettingsRoute
    }
    '/__authted/$org/settings/support': {
      id: '/__authted/$org/settings/support'
      path: '/support'
      fullPath: '/$org/settings/support'
      preLoaderRoute: typeof _authtedOrgSettingsSupportRouteImport
      parentRoute: typeof _authtedOrgSettingsRoute
    }
    '/__authted/$org/settings/security': {
      id: '/__authted/$org/settings/security'
      path: '/security'
      fullPath: '/$org/settings/security'
      preLoaderRoute: typeof _authtedOrgSettingsSecurityRouteImport
      parentRoute: typeof _authtedOrgSettingsRoute
    }
    '/__authted/$org/settings/general': {
      id: '/__authted/$org/settings/general'
      path: '/general'
      fullPath: '/$org/settings/general'
      preLoaderRoute: typeof _authtedOrgSettingsGeneralRouteImport
      parentRoute: typeof _authtedOrgSettingsRoute
    }
    '/__authted/$org/settings/billing': {
      id: '/__authted/$org/settings/billing'
      path: '/billing'
      fullPath: '/$org/settings/billing'
      preLoaderRoute: typeof _authtedOrgSettingsBillingRouteImport
      parentRoute: typeof _authtedOrgSettingsRoute
    }
    '/__authted/$org/telmentary/$projectId/': {
      id: '/__authted/$org/telmentary/$projectId/'
      path: '/'
      fullPath: '/$org/telmentary/$projectId/'
      preLoaderRoute: typeof _authtedOrgTelmentaryProjectIdIndexRouteImport
      parentRoute: typeof _authtedOrgTelmentaryProjectIdRoute
    }
    '/__authted/$org/telmentary/$projectId/traces': {
      id: '/__authted/$org/telmentary/$projectId/traces'
      path: '/traces'
      fullPath: '/$org/telmentary/$projectId/traces'
      preLoaderRoute: typeof _authtedOrgTelmentaryProjectIdTracesRouteImport
      parentRoute: typeof _authtedOrgTelmentaryProjectIdRoute
    }
    '/__authted/$org/telmentary/$projectId/settings': {
      id: '/__authted/$org/telmentary/$projectId/settings'
      path: '/settings'
      fullPath: '/$org/telmentary/$projectId/settings'
      preLoaderRoute: typeof _authtedOrgTelmentaryProjectIdSettingsRouteImport
      parentRoute: typeof _authtedOrgTelmentaryProjectIdRoute
    }
    '/__authted/$org/telmentary/$projectId/logs': {
      id: '/__authted/$org/telmentary/$projectId/logs'
      path: '/logs'
      fullPath: '/$org/telmentary/$projectId/logs'
      preLoaderRoute: typeof _authtedOrgTelmentaryProjectIdLogsRouteImport
      parentRoute: typeof _authtedOrgTelmentaryProjectIdRoute
    }
    '/__authted/$org/telmentary/$projectId/analytics': {
      id: '/__authted/$org/telmentary/$projectId/analytics'
      path: '/analytics'
      fullPath: '/$org/telmentary/$projectId/analytics'
      preLoaderRoute: typeof _authtedOrgTelmentaryProjectIdAnalyticsRouteImport
      parentRoute: typeof _authtedOrgTelmentaryProjectIdRoute
    }
    '/__authted/$org/telmentary/$projectId/alerts': {
      id: '/__authted/$org/telmentary/$projectId/alerts'
      path: '/alerts'
      fullPath: '/$org/telmentary/$projectId/alerts'
      preLoaderRoute: typeof _authtedOrgTelmentaryProjectIdAlertsRouteImport
      parentRoute: typeof _authtedOrgTelmentaryProjectIdRoute
    }
    '/__authted/$org/telmentary/$projectId/settings/': {
      id: '/__authted/$org/telmentary/$projectId/settings/'
      path: '/'
      fullPath: '/$org/telmentary/$projectId/settings/'
      preLoaderRoute: typeof _authtedOrgTelmentaryProjectIdSettingsIndexRouteImport
      parentRoute: typeof _authtedOrgTelmentaryProjectIdSettingsRoute
    }
    '/__authted/$org/telmentary/$projectId/settings/integrations': {
      id: '/__authted/$org/telmentary/$projectId/settings/integrations'
      path: '/integrations'
      fullPath: '/$org/telmentary/$projectId/settings/integrations'
      preLoaderRoute: typeof _authtedOrgTelmentaryProjectIdSettingsIntegrationsRouteImport
      parentRoute: typeof _authtedOrgTelmentaryProjectIdSettingsRoute
    }
    '/__authted/$org/telmentary/$projectId/settings/general': {
      id: '/__authted/$org/telmentary/$projectId/settings/general'
      path: '/general'
      fullPath: '/$org/telmentary/$projectId/settings/general'
      preLoaderRoute: typeof _authtedOrgTelmentaryProjectIdSettingsGeneralRouteImport
      parentRoute: typeof _authtedOrgTelmentaryProjectIdSettingsRoute
    }
    '/__authted/$org/telmentary/$projectId/settings/data-retention': {
      id: '/__authted/$org/telmentary/$projectId/settings/data-retention'
      path: '/data-retention'
      fullPath: '/$org/telmentary/$projectId/settings/data-retention'
      preLoaderRoute: typeof _authtedOrgTelmentaryProjectIdSettingsDataRetentionRouteImport
      parentRoute: typeof _authtedOrgTelmentaryProjectIdSettingsRoute
    }
    '/__authted/$org/telmentary/$projectId/settings/api-keys': {
      id: '/__authted/$org/telmentary/$projectId/settings/api-keys'
      path: '/api-keys'
      fullPath: '/$org/telmentary/$projectId/settings/api-keys'
      preLoaderRoute: typeof _authtedOrgTelmentaryProjectIdSettingsApiKeysRouteImport
      parentRoute: typeof _authtedOrgTelmentaryProjectIdSettingsRoute
    }
    '/__authted/$org/telmentary/$projectId/settings/alerts': {
      id: '/__authted/$org/telmentary/$projectId/settings/alerts'
      path: '/alerts'
      fullPath: '/$org/telmentary/$projectId/settings/alerts'
      preLoaderRoute: typeof _authtedOrgTelmentaryProjectIdSettingsAlertsRouteImport
      parentRoute: typeof _authtedOrgTelmentaryProjectIdSettingsRoute
    }
    '/__authted/$org/telmentary/$projectId/settings/access-control': {
      id: '/__authted/$org/telmentary/$projectId/settings/access-control'
      path: '/access-control'
      fullPath: '/$org/telmentary/$projectId/settings/access-control'
      preLoaderRoute: typeof _authtedOrgTelmentaryProjectIdSettingsAccessControlRouteImport
      parentRoute: typeof _authtedOrgTelmentaryProjectIdSettingsRoute
    }
  }
}

interface _authtedOrgSettingsRouteChildren {
  _authtedOrgSettingsBillingRoute: typeof _authtedOrgSettingsBillingRoute
  _authtedOrgSettingsGeneralRoute: typeof _authtedOrgSettingsGeneralRoute
  _authtedOrgSettingsSecurityRoute: typeof _authtedOrgSettingsSecurityRoute
  _authtedOrgSettingsSupportRoute: typeof _authtedOrgSettingsSupportRoute
  _authtedOrgSettingsTeamRoute: typeof _authtedOrgSettingsTeamRoute
  _authtedOrgSettingsIndexRoute: typeof _authtedOrgSettingsIndexRoute
}

const _authtedOrgSettingsRouteChildren: _authtedOrgSettingsRouteChildren = {
  _authtedOrgSettingsBillingRoute: _authtedOrgSettingsBillingRoute,
  _authtedOrgSettingsGeneralRoute: _authtedOrgSettingsGeneralRoute,
  _authtedOrgSettingsSecurityRoute: _authtedOrgSettingsSecurityRoute,
  _authtedOrgSettingsSupportRoute: _authtedOrgSettingsSupportRoute,
  _authtedOrgSettingsTeamRoute: _authtedOrgSettingsTeamRoute,
  _authtedOrgSettingsIndexRoute: _authtedOrgSettingsIndexRoute,
}

const _authtedOrgSettingsRouteWithChildren =
  _authtedOrgSettingsRoute._addFileChildren(_authtedOrgSettingsRouteChildren)

interface _authtedOrgTelmentaryProjectIdSettingsRouteChildren {
  _authtedOrgTelmentaryProjectIdSettingsAccessControlRoute: typeof _authtedOrgTelmentaryProjectIdSettingsAccessControlRoute
  _authtedOrgTelmentaryProjectIdSettingsAlertsRoute: typeof _authtedOrgTelmentaryProjectIdSettingsAlertsRoute
  _authtedOrgTelmentaryProjectIdSettingsApiKeysRoute: typeof _authtedOrgTelmentaryProjectIdSettingsApiKeysRoute
  _authtedOrgTelmentaryProjectIdSettingsDataRetentionRoute: typeof _authtedOrgTelmentaryProjectIdSettingsDataRetentionRoute
  _authtedOrgTelmentaryProjectIdSettingsGeneralRoute: typeof _authtedOrgTelmentaryProjectIdSettingsGeneralRoute
  _authtedOrgTelmentaryProjectIdSettingsIntegrationsRoute: typeof _authtedOrgTelmentaryProjectIdSettingsIntegrationsRoute
  _authtedOrgTelmentaryProjectIdSettingsIndexRoute: typeof _authtedOrgTelmentaryProjectIdSettingsIndexRoute
}

const _authtedOrgTelmentaryProjectIdSettingsRouteChildren: _authtedOrgTelmentaryProjectIdSettingsRouteChildren =
  {
    _authtedOrgTelmentaryProjectIdSettingsAccessControlRoute:
      _authtedOrgTelmentaryProjectIdSettingsAccessControlRoute,
    _authtedOrgTelmentaryProjectIdSettingsAlertsRoute:
      _authtedOrgTelmentaryProjectIdSettingsAlertsRoute,
    _authtedOrgTelmentaryProjectIdSettingsApiKeysRoute:
      _authtedOrgTelmentaryProjectIdSettingsApiKeysRoute,
    _authtedOrgTelmentaryProjectIdSettingsDataRetentionRoute:
      _authtedOrgTelmentaryProjectIdSettingsDataRetentionRoute,
    _authtedOrgTelmentaryProjectIdSettingsGeneralRoute:
      _authtedOrgTelmentaryProjectIdSettingsGeneralRoute,
    _authtedOrgTelmentaryProjectIdSettingsIntegrationsRoute:
      _authtedOrgTelmentaryProjectIdSettingsIntegrationsRoute,
    _authtedOrgTelmentaryProjectIdSettingsIndexRoute:
      _authtedOrgTelmentaryProjectIdSettingsIndexRoute,
  }

const _authtedOrgTelmentaryProjectIdSettingsRouteWithChildren =
  _authtedOrgTelmentaryProjectIdSettingsRoute._addFileChildren(
    _authtedOrgTelmentaryProjectIdSettingsRouteChildren,
  )

interface _authtedOrgTelmentaryProjectIdRouteChildren {
  _authtedOrgTelmentaryProjectIdAlertsRoute: typeof _authtedOrgTelmentaryProjectIdAlertsRoute
  _authtedOrgTelmentaryProjectIdAnalyticsRoute: typeof _authtedOrgTelmentaryProjectIdAnalyticsRoute
  _authtedOrgTelmentaryProjectIdLogsRoute: typeof _authtedOrgTelmentaryProjectIdLogsRoute
  _authtedOrgTelmentaryProjectIdSettingsRoute: typeof _authtedOrgTelmentaryProjectIdSettingsRouteWithChildren
  _authtedOrgTelmentaryProjectIdTracesRoute: typeof _authtedOrgTelmentaryProjectIdTracesRoute
  _authtedOrgTelmentaryProjectIdIndexRoute: typeof _authtedOrgTelmentaryProjectIdIndexRoute
}

const _authtedOrgTelmentaryProjectIdRouteChildren: _authtedOrgTelmentaryProjectIdRouteChildren =
  {
    _authtedOrgTelmentaryProjectIdAlertsRoute:
      _authtedOrgTelmentaryProjectIdAlertsRoute,
    _authtedOrgTelmentaryProjectIdAnalyticsRoute:
      _authtedOrgTelmentaryProjectIdAnalyticsRoute,
    _authtedOrgTelmentaryProjectIdLogsRoute:
      _authtedOrgTelmentaryProjectIdLogsRoute,
    _authtedOrgTelmentaryProjectIdSettingsRoute:
      _authtedOrgTelmentaryProjectIdSettingsRouteWithChildren,
    _authtedOrgTelmentaryProjectIdTracesRoute:
      _authtedOrgTelmentaryProjectIdTracesRoute,
    _authtedOrgTelmentaryProjectIdIndexRoute:
      _authtedOrgTelmentaryProjectIdIndexRoute,
  }

const _authtedOrgTelmentaryProjectIdRouteWithChildren =
  _authtedOrgTelmentaryProjectIdRoute._addFileChildren(
    _authtedOrgTelmentaryProjectIdRouteChildren,
  )

interface _authtedOrgTelmentaryRouteChildren {
  _authtedOrgTelmentaryProjectIdRoute: typeof _authtedOrgTelmentaryProjectIdRouteWithChildren
  _authtedOrgTelmentaryIndexRoute: typeof _authtedOrgTelmentaryIndexRoute
}

const _authtedOrgTelmentaryRouteChildren: _authtedOrgTelmentaryRouteChildren = {
  _authtedOrgTelmentaryProjectIdRoute:
    _authtedOrgTelmentaryProjectIdRouteWithChildren,
  _authtedOrgTelmentaryIndexRoute: _authtedOrgTelmentaryIndexRoute,
}

const _authtedOrgTelmentaryRouteWithChildren =
  _authtedOrgTelmentaryRoute._addFileChildren(
    _authtedOrgTelmentaryRouteChildren,
  )

interface _authtedOrgRouteChildren {
  _authtedOrgSettingsRoute: typeof _authtedOrgSettingsRouteWithChildren
  _authtedOrgTelmentaryRoute: typeof _authtedOrgTelmentaryRouteWithChildren
  _authtedOrgIndexRoute: typeof _authtedOrgIndexRoute
}

const _authtedOrgRouteChildren: _authtedOrgRouteChildren = {
  _authtedOrgSettingsRoute: _authtedOrgSettingsRouteWithChildren,
  _authtedOrgTelmentaryRoute: _authtedOrgTelmentaryRouteWithChildren,
  _authtedOrgIndexRoute: _authtedOrgIndexRoute,
}

const _authtedOrgRouteWithChildren = _authtedOrgRoute._addFileChildren(
  _authtedOrgRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _authedRoute: _authedRoute,
  OnboardingRoute: OnboardingRoute,
  _authtedOrgRoute: _authtedOrgRouteWithChildren,
  _authtedOrganizationsRoute: _authtedOrganizationsRoute,
  ApiDemoNamesRoute: ApiDemoNamesRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
