import { createFileRoute } from '@tanstack/react-router';
import { Client } from 'pg';

const db = new Client({
  connectionString: process.env.DATABASE_URL,
});

// Initialize database connection
let isConnected = false;
async function ensureConnection() {
  if (!isConnected) {
    await db.connect();
    isConnected = true;
  }
}

export const Route = createFileRoute('/api/projects')({
  server: {
    handlers: {
      GET: async ({ request }: any) => {
        try {
          await ensureConnection();

          const url = new URL(request.url);
          const org_slug = url.searchParams.get('org_slug');
          const slug = url.searchParams.get('slug');

          let result;
          if (slug) {
            // Get specific project by slug only
            result = await db.query(
              `SELECT id, name, slug, org_id, api_key, created_at, updated_at 
               FROM projects 
               WHERE slug = $1`,
              [slug]
            );

            if (result.rows.length === 0) {
              return Response.json({ error: 'Project not found' }, { status: 404 });
            }

            return Response.json({
              data: result.rows[0],
            });
          } else if (org_slug) {
            // Get all projects for org by org slug
            result = await db.query(
              `SELECT p.id, p.name, p.slug, p.org_id, p.api_key, p.created_at, p.updated_at 
               FROM projects p
               JOIN organization o ON p.org_id = o.id
               WHERE o.slug = $1 
               ORDER BY p.updated_at DESC`,
              [org_slug]
            );

            return Response.json({
              data: result.rows,
            });
          } else {
            return Response.json(
              { error: 'Missing required parameter: org_slug or slug' },
              { status: 400 }
            );
          }
        } catch (error) {
          console.error('Error fetching projects:', error);
          return Response.json(
            { error: error instanceof Error ? error.message : 'Unknown error' },
            { status: 500 }
          );
        }
      },

      POST: async ({ request }: any) => {
        try {
          await ensureConnection();

          const body = await request.json();
          const { name, org_id } = body;

          if (!name || !org_id) {
            return Response.json(
              { error: 'Missing required fields: name and org_id' },
              { status: 400 }
            );
          }

          // Generate API key and slug
          const apiKey = `pw_${Math.random().toString(36).substring(2, 15)}${Math.random().toString(36).substring(2, 15)}`;
          const slug = name.toLowerCase().replace(/\s+/g, '-');

          // Insert project into database (UUID generated by database)
          const result = await db.query(
            `INSERT INTO projects (name, slug, org_id, api_key) 
             VALUES ($1, $2, $3, $4)
             RETURNING id, name, slug, org_id, api_key`,
            [name, slug, org_id, apiKey]
          );

          const project = result.rows[0];

          return Response.json({
            data: {
              id: project.id,
              name: project.name,
              slug: project.slug,
              org_id: project.org_id,
              api_key: project.api_key,
            },
          });
        } catch (error) {
          console.error('Error creating project:', error);
          return Response.json(
            { error: error instanceof Error ? error.message : 'Unknown error' },
            { status: 500 }
          );
        }
      },
    },
  },
});
